### ISSUE TITLE
Distribution files are missing directives

### ISSUE THREAD

**Issue by jawgardner** [spike886/angular-touch-widgets#3]
Thank you for a wonderful set of widgets! 

I think your distribution files we get via bower are missing some of the directives, for example color-wheel. I had to replace the contents of angular-touch-widgets.js with the version you use in your demo to get them to work.

Thanks again for a wonderful set of components. Your color wheel, can i say, is the best color-picker for ionic there is.

**Comment by spike886** [comment]
It was an error on the demo page using a deprecated version.
I just updated the demo page and added documentation to prevent this mistakes on the future
